#!/bin/sh

erlang_initialize()
{
  package define \
    file "otp_src_${package_version}.${archive_format}" \
    dir "otp_src_${package_version}"

  configure_flags+=(
    --enable-hipe
    --enable-smp-support
    --enable-threads
    --enable-kernel-poll
  )

  if os is darwin
  then configure_flags+=("--enable-darwin-64bit")
  fi
}

