#!/usr/bin/env bash

# perl-5.12.3$ sh Configure -h
#
#Usage: Configure [-dehrsEKOSV] [-f config.sh] [-D symbol] [-D symbol=value]
#                 [-U symbol] [-U symbol=] [-A command:symbol...]
#  -d : use defaults for all answers.
#  -e : go on without questioning past the production of config.sh.
#  -f : specify an alternate default configuration file.
#  -h : print this help message and exit (with an error status).
#  -r : reuse C symbols value if possible (skips costly nm extraction).
#  -s : silent mode, only echoes questions and essential information.
#  -D : define symbol to have some value:
#         -D symbol         symbol gets the value 'define'
#         -D symbol=value   symbol gets the value 'value'
#       common used examples (see INSTALL for more info):
#         -Duse64bitint            use 64bit integers
#         -Duse64bitall            use 64bit integers and pointers
#         -Dusethreads             use thread support
#         -Dinc_version_list=none  do not include older perl trees in @INC
#         -DEBUGGING=none          DEBUGGING options
#         -Dcc=gcc                 choose your compiler
#         -Dprefix=/opt/perl5      choose your destination
#  -E : stop at the end of questions, after having produced config.sh.
#  -K : do not use unless you know what you are doing.
#  -O : let -D and -U override definitions from loaded configuration file.
#  -S : perform variable substitutions on all .SH files (can mix with -f)
#  -U : undefine symbol:
#         -U symbol    symbol gets the value 'undef'
#         -U symbol=   symbol gets completely empty
#       e.g.:  -Uversiononly
#  -A : manipulate symbol after the platform specific hints have been applied:
#         -A append:symbol=value   append value to symbol
#         -A symbol=value          like append:, but with a separating space
#         -A define:symbol=value   define symbol to have value
#         -A clear:symbol          define symbol to be ''
#         -A define:symbol         define symbol to be 'define'
#         -A eval:symbol=value     define symbol to be eval of value
#         -A prepend:symbol=value  prepend value to symbol
#         -A undef:symbol          define symbol to be 'undef'
#         -A undef:symbol=         define symbol to be ''
#       e.g.:  -A prepend:libswanted='cl pthread '
#              -A ccflags=-DSOME_MACRO
#  -V : print version number and exit (with a zero status).
#

perl_configure()
{
	sh Configure -de -Dprefix="${install_path}"
}
