#!/bin/sh

lua_build()
{
  log "Building ${package_name} ${package_version}"
  # Override make command based on platform type.
  if os is linux
  then
    make linux
  elif os is darwin
  then
    make darwin
  elif os is solaris
  then
    make solaris
  elif os is aix
  then
    make aix
  else # posix...
    make posix
  fi
}

lua_install()
{
  log "Installing ${package_name} ${package_version}"
  (
  paths enter "src/"
  files copy to "${install_path}/bin" lua luac mode 0755
  )

  # TODO: Do we want any of the library files?
}
