#!/usr/bin/env bash

package_dependencies=( ncurses ) # openssl

unset LDCONFIG CFLAGS

configure_flags+=(
  --prefix="${install_path}"
  --enable-hipe
  --enable-smp-support
  --enable-threads
  --enable-kernel-poll
)

if os_is_darwin
then
  configure_flags+=("--enable-darwin-64bit")
fi

# It is important to build single threaded,
#   which is very amusing given it is for Erlang...
make_flags="-j1"

